# Generated by Django 4.2.3 on 2023-11-14 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_card', models.CharField(blank=True, help_text="User's ID card number", max_length=13, null=True)),
                ('role', models.CharField(choices=[('Superuser', 'SuperUser'), ('Admin', 'Administrator'), ('Driver', 'Driver')], default='Driver', help_text="User's role in the system", max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
