# Generated by Django 4.2.7 on 2023-12-20 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Superuser', 'SuperUser'), ('Admin', 'Administrator'), ('Driver', 'Driver'), ('TransportManager', 'Transport Manager'), ('Secretary', 'Secretary'), ('Dispatcher', 'Dispatcher'), ('Maintenance', 'Maintenance')], help_text="User's role", max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_accounts',
            field=models.ManyToManyField(blank=True, to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(help_text="User's roles in the system", to='users.role'),
        ),
    ]
