# Generated by Django 4.2.7 on 2023-12-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='parent_accounts',
            field=models.ManyToManyField(blank=True, related_name='child_accounts', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Superuser', 'SuperUser'), ('Admin', 'Administrator'), ('Driver', 'Driver'), ('TransportManager', 'Transport Manager'), ('Secretary', 'Secretary'), ('Dispatcher', 'Dispatcher'), ('Maintenance', 'Maintenance')], help_text="User's role", max_length=32, unique=True),
        ),
    ]
