# Generated by Django 4.2.10 on 2024-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text="User's birth date", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Bachelor', 'Bachelor'), ('University', 'University')], default='Primary', help_text="User's education level", max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='home_address',
            field=models.CharField(blank=True, help_text="User's home address", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Single', 'Single'), ('Free Union', 'Free Union'), ('Widowed', 'Widowed')], default='Single', help_text="User's marital status", max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, help_text="User's photo", null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Superuser', 'SuperUser'), ('Admin', 'Administrator'), ('Driver', 'Driver'), ('TransportManager', 'Transport Manager'), ('Secretary', 'Secretary'), ('Dispatcher', 'Dispatcher'), ('Maintenance', 'Maintenance'), ('Supervisor', 'Supervisor'), ('Mechanic', 'Mechanic'), ('Logistics', 'Logistics')], help_text="User's role", max_length=32, unique=True),
        ),
    ]
