# Generated by Django 4.2.10 on 2024-03-25 17:11

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_birth_date_customuser_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, help_text="User's photo", null=True, upload_to=users.utils.path_and_rename),
        ),
    ]
