# Generated by Django 4.2.3 on 2023-11-14 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude of the location.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lng', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude of the location.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('time', models.PositiveBigIntegerField(help_text='Time when the coordinates were recorded.')),
                ('address', models.TextField(blank=True, help_text='Geographic address where the alarm occurred.', null=True)),
                ('alarm_code', models.CharField(choices=[('ACCOFF', 'Parada'), ('ACCON', 'Inicio'), ('OFFLINETIMEOUT', 'Tiempo de espera sin conexión'), ('STAYTIMEOUT', 'Tiempo de espera de estancia'), ('REMOVE', 'Desmontaje, sensor de luz, fallo de alimentación, enchufar y desenchufar'), ('LOWVOT', 'Baja electricidad'), ('ERYA', 'Segunda carga'), ('FENCEIN', 'Entrar en la cerca'), ('FENCEOUT', 'Fuera de la cerca'), ('SEP', 'Separado'), ('SOS', 'Alarma SOS'), ('OVERSPEED', 'Alarma de exceso de velocidad'), ('HOME', 'Residencia permanente anormal (casa)'), ('COMPANY', 'Residencia permanente anormal (empresa)'), ('CRASH', 'Alarma de colisión'), ('SHAKE', 'Vibración'), ('ACCELERATION', 'Aceleración rápida'), ('DECELERATION', 'Desaceleración rápida'), ('TURN', 'Giro brusco'), ('FASTACCELERATION', 'Aceleración máxima'), ('SHARPTURN', 'Giro brusco'), ('TURNOVER', 'Volcar'), ('FASTDECELERATION', 'Desaceleración rápida'), ('REMOVECONTINUOUSLY', 'Alarma de desmontaje continuo, alarma de sensor de luz y fallo de alimentación'), ('SHIFT', 'Alarma de movimiento'), ('AREAOUT', 'Alarma de salida de área'), ('AREAIN', 'Alarma de entrada a área'), ('EXTERNALLOWBATTERY', 'Alarma de baja tensión de la batería externa'), ('XINHAOPINBI', 'Alarma de bloqueo de señal'), ('PSEUDOBASESTATION', 'Alarma de estación base falsa'), ('ONLINE', 'Alarma en línea'), ('ABNORMALACCUMULATION', 'Alarma de acumulación anormal'), ('RISKPLACE', 'Alarma de permanencia en lugar de riesgo'), ('VINMISMATCH', 'Alarma de coincidencia incorrecta de VIN'), ('SHORTMILES', 'Alarma de kilometraje ultracorto'), ('LONGMILES', 'Alarma de kilometraje super largo'), ('TRAIL', 'Alarma de remolque'), ('MULTIPLAYER', 'Alarma de jugador múltiple'), ('OPENCOVER', 'Alarma de tapa abierta'), ('POWERON', 'Alarma de encendido'), ('POWEROFF', 'Alarma de apagado')], default='ACCOFF', help_text='Code representing the type of alarm.', max_length=20)),
                ('alarm_type', models.IntegerField(help_text='Integer representing the type of alarm.')),
                ('course', models.IntegerField(blank=True, help_text='Course of the device when the alarm occurred.', null=True)),
                ('device_type', models.IntegerField(help_text='Integer representing the type of device that triggered the alarm.')),
                ('position_type', models.CharField(blank=True, help_text='Type of position data associated with the alarm.', max_length=20, null=True)),
                ('speed', models.IntegerField(blank=True, help_text='Speed of the device when the alarm occurred.', null=True)),
                ('device', models.ForeignKey(help_text='Device that triggered the alarm.', on_delete=django.db.models.deletion.PROTECT, to='devices.device')),
            ],
            options={
                'verbose_name': 'Alarm',
                'verbose_name_plural': 'Alarms',
            },
        ),
    ]
