# Generated by Django 4.2.11 on 2024-05-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarm_code',
            field=models.CharField(choices=[('ACCOFF', 'Parada'), ('ACCON', 'Inicio'), ('OFFLINETIMEOUT', 'Tiempo de espera sin conexión'), ('STAYTIMEOUT', 'Tiempo de espera de estancia'), ('REMOVE', 'Desmontaje, sensor de luz, fallo de alimentación, enchufar y desenchufar'), ('LOWVOT', 'Baja electricidad'), ('ERYA', 'Segunda carga'), ('FENCEIN', 'Entrar en la cerca'), ('FENCEOUT', 'Fuera de la cerca'), ('SEP', 'Separado'), ('SOS', 'Alarma SOS'), ('OVERSPEED', 'Alarma de exceso de velocidad'), ('HOME', 'Residencia permanente anormal (casa)'), ('COMPANY', 'Residencia permanente anormal (empresa)'), ('CRASH', 'Alarma de colisión'), ('SHAKE', 'Vibración'), ('ACCELERATION', 'Aceleración rápida'), ('DECELERATION', 'Desaceleración rápida'), ('TURN', 'Giro brusco'), ('FASTACCELERATION', 'Aceleración máxima'), ('SHARPTURN', 'Giro brusco'), ('TURNOVER', 'Volcar'), ('FASTDECELERATION', 'Desaceleración rápida'), ('REMOVECONTINUOUSLY', 'Alarma de desmontaje continuo, alarma de sensor de luz y fallo de alimentación'), ('SHIFT', 'Alarma de movimiento'), ('AREAOUT', 'Alarma de salida de área'), ('AREAIN', 'Alarma de entrada a área'), ('EXTERNALLOWBATTERY', 'Alarma de baja tensión de la batería externa'), ('XINHAOPINBI', 'Alarma de bloqueo de señal'), ('PSEUDOBASESTATION', 'Alarma de estación base falsa'), ('ONLINE', 'Alarma en línea'), ('ABNORMALACCUMULATION', 'Alarma de acumulación anormal'), ('RISKPLACE', 'Alarma de permanencia en lugar de riesgo'), ('VINMISMATCH', 'Alarma de coincidencia incorrecta de VIN'), ('SHORTMILES', 'Alarma de kilometraje ultracorto'), ('LONGMILES', 'Alarma de kilometraje super largo'), ('TRAIL', 'Alarma de remolque'), ('MULTIPLAYER', 'Alarma de jugador múltiple'), ('OPENCOVER', 'Alarma de tapa abierta'), ('POWERON', 'Alarma de encendido'), ('POWEROFF', 'Alarma de apagado'), ('MAGNETISM', 'Detección de campos magnéticos'), ('BLUETOOTH', 'Bluetooth'), ('UNKNOWN', 'UNKNOWN'), ('DRIVING', 'Conduciendo'), ('DRIVINGBYME', 'Conduciendo según yo'), ('STOPPED', 'Detenido'), ('STOPPEDBYME', 'Detenido según yo'), ('AUXILIARYACTIVITIES', 'Actividades Auxiliares')], default='ACCOFF', help_text='Code representing the type of alarm.', max_length=20),
        ),
    ]
