# Generated by Django 4.2.3 on 2023-11-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('imei', models.CharField(help_text="The device's International Mobile Equipment Identity (IMEI) number.", max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Device IMEI')),
                ('user_name', models.CharField(help_text='The name of the user associated with the device.', max_length=255, verbose_name='User Name')),
                ('car_owner', models.CharField(blank=True, help_text='The name of the car owner. This field can be left blank.', max_length=255, null=True, verbose_name='Car Owner')),
                ('license_number', models.CharField(blank=True, help_text='The license number of the car. This field can be left blank.', max_length=255, null=True, verbose_name='License Number')),
                ('vin', models.CharField(blank=True, help_text='The Vehicle Identification Number (VIN) of the car. This field can be left blank.', max_length=255, null=True, verbose_name='VIN')),
                ('is_tracking_alarms', models.BooleanField(default=False, help_text='A flag indicating if the device is tracking alarms.', verbose_name='Is Tracking Alarms')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
            },
        ),
    ]
