# Generated by Django 4.2.3 on 2023-11-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_time_tracked',
            field=models.PositiveBigIntegerField(default=0, help_text='The last time when the device alarms were tracked.', verbose_name='Last Time Tracked'),
        ),
    ]
