# Generated by Django 4.2.11 on 2024-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_time_tracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='provider',
            field=models.CharField(choices=[('WanWayTech', 'WanWayTech'), ('WhatsGPS', 'WhatsGPS')], default='WanWayTech', help_text='The provider of the device.', max_length=50, verbose_name='Provider'),
        ),
    ]
