# Generated by Django 4.2.11 on 2024-05-06 15:36

from django.db import migrations, models
import django.db.models.deletion
import licenses.validators
import uuid
import vehicles.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0005_vehicle_front_photo_vehicle_heavy_transport_permit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID of the vehicle registration', primary_key=True, serialize=False)),
                ('registration_document', models.FileField(blank=True, help_text='Vehicle registration document', null=True, upload_to=vehicles.utils.path_and_rename)),
                ('issue_date', models.DateField(help_text='Issue date of the vehicle registration', validators=[licenses.validators.validate_issue_date])),
                ('expiry_date', models.DateField(help_text='Expiry date of the vehicle registration', validators=[licenses.validators.validate_license_validity])),
                ('vehicle', models.ForeignKey(help_text='The vehicle that this registration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Registration',
                'verbose_name_plural': 'Vehicle Registrations',
            },
        ),
    ]
