# Generated by Django 4.2.11 on 2024-05-02 04:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_customuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude of the location.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lng', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude of the location.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('name', models.CharField(blank=True, help_text='Name of the position.', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the route.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the route.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the route.')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_routes', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'verbose_name': 'User Route',
                'verbose_name_plural': 'User Routes',
            },
        ),
        migrations.CreateModel(
            name='RoutePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='The order of the position in the route.')),
                ('alias', models.CharField(blank=True, help_text='Alias for the position.', max_length=200)),
                ('position', models.ForeignKey(help_text='The position in the route.', on_delete=django.db.models.deletion.CASCADE, to='routes.position')),
                ('route', models.ForeignKey(help_text='The route that the position belongs to.', on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='positions',
            field=models.ManyToManyField(help_text='Positions that make up the route.', through='routes.RoutePosition', to='routes.position'),
        ),
    ]
