# Generated by Django 4.2.7 on 2024-01-31 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_phonenumber'),
        ('vehicles', '0004_alter_battery_registration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date_unix', models.PositiveBigIntegerField(help_text='The issue date of the work order in Unix format.', verbose_name='Issue date')),
                ('maintenance_type', models.CharField(help_text='The type of maintenance to be performed.', max_length=255, verbose_name='Maintenance type')),
                ('work_type', models.TextField(help_text='The type of work to be performed.', verbose_name='Work type')),
                ('created_by', models.ForeignKey(help_text='The user who created the work order.', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_created', to='users.customuser')),
                ('responsible', models.ForeignKey(help_text='The user responsible for the work order.', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_responsible', to='users.customuser')),
                ('vehicle', models.ForeignKey(help_text='The vehicle associated with the work order.', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Work order',
                'verbose_name_plural': 'Work orders',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_completed', 'Not Completed')], default='pending', help_text='The status of the work order.', max_length=20, verbose_name='Status')),
                ('change_date_unix', models.PositiveBigIntegerField(help_text='The date when the status was updated, in Unix format.', verbose_name='Change date')),
                ('responsible_notes', models.TextField(blank=True, help_text='Any notes from the responsible person.', verbose_name='Responsible notes')),
                ('change_registered_by', models.ForeignKey(help_text='The user who registered the change.', on_delete=django.db.models.deletion.PROTECT, related_name='work_order_completions', to='users.customuser')),
                ('work_order', models.ForeignKey(help_text='The work order that this completion record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Work order completion',
                'verbose_name_plural': 'Work order completions',
            },
        ),
    ]
