# Generated by Django 4.2.11 on 2024-05-02 06:32

from django.db import migrations, models
import django.db.models.deletion
import movement_orders.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mileage', '0002_alter_mileage_unit'),
        ('users', '0006_alter_customuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosureMovementOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the closure of the closure movement order.', primary_key=True, serialize=False)),
                ('confirmation_time', models.PositiveIntegerField(help_text='The confirmation time of the closure in Unix time format.')),
                ('arrival_time_unix', models.IntegerField(help_text='The arrival time of the vehicle at the destination in Unix time format.')),
                ('compliance', models.BooleanField(help_text='Whether the movement order was complied with.')),
                ('extra_details', models.CharField(blank=True, help_text='Any extra details about the closure of the movement order.', max_length=1500)),
                ('had_incident', models.BooleanField(default=False, help_text='Whether the movement order had any incidents.')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the movement order.', primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Description of the incident.', max_length=2000)),
                ('incident_time_unix', models.IntegerField(help_text='The time of the incident in Unix time format.')),
                ('resolved', models.BooleanField(default=False, help_text='Whether the incident has been resolved.')),
                ('image', models.ImageField(blank=True, help_text='Image related to the incident.', null=True, upload_to=movement_orders.utils.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='MovementOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the movement order.', primary_key=True, serialize=False)),
                ('created_at', models.IntegerField(help_text='The creation time of the movement order in Unix time format.')),
                ('departure_details', models.CharField(help_text='Details about the departure of the movement order.', max_length=1500)),
                ('departure_time_unix', models.PositiveIntegerField(help_text='The departure time of the movement order in Unix time format.')),
                ('estimated_arrival_time_unix', models.PositiveIntegerField(blank=True, help_text='The estimated arrival time of the movement order in Unix time format.', null=True)),
                ('authorized_by', models.ForeignKey(help_text='The user who authorized the movement order.', on_delete=django.db.models.deletion.CASCADE, related_name='authorized_orders', to='users.customuser')),
                ('departure_mileage', models.ForeignKey(help_text='The mileage of the vehicle at the start of the movement order.', on_delete=django.db.models.deletion.CASCADE, to='mileage.mileage')),
                ('driver', models.ForeignKey(help_text='The driver of the vehicle.', on_delete=django.db.models.deletion.CASCADE, related_name='driven_orders', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='MovementOrderState',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the movement order state.', primary_key=True, serialize=False)),
                ('state', models.CharField(help_text='The state of the movement order.', max_length=200)),
                ('timestamp_unix', models.PositiveIntegerField(help_text='The time at which this state was recorded in Unix time format.')),
                ('movement_order', models.ForeignKey(help_text='The movement order this state is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='movement_orders.movementorder')),
                ('set_by', models.ForeignKey(help_text='The user who set this state.', on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
