# Generated by Django 4.2.11 on 2024-05-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mileage', '0002_alter_mileage_unit'),
        ('vehicles', '0005_vehicle_front_photo_vehicle_heavy_transport_permit_and_more'),
        ('movement_orders', '0001_initial'),
        ('users', '0006_alter_customuser_photo'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementorder',
            name='itinerary',
            field=models.ForeignKey(help_text='The route of the movement order.', on_delete=django.db.models.deletion.CASCADE, to='routes.route'),
        ),
        migrations.AddField(
            model_name='movementorder',
            name='vehicle',
            field=models.ForeignKey(help_text='The vehicle used in the movement order.', on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='incident',
            name='movement_order',
            field=models.ForeignKey(help_text='The movement order during which the incident occurred.', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='movement_orders.movementorder'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(help_text='The user who reported the incident.', on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AddField(
            model_name='closuremovementorder',
            name='arrival_mileage',
            field=models.ForeignKey(help_text='The mileage of the vehicle at the end of the movement order.', on_delete=django.db.models.deletion.CASCADE, to='mileage.mileage'),
        ),
        migrations.AddField(
            model_name='closuremovementorder',
            name='movement_order',
            field=models.ForeignKey(help_text='The movement order being closed.', on_delete=django.db.models.deletion.CASCADE, to='movement_orders.movementorder'),
        ),
        migrations.AddField(
            model_name='closuremovementorder',
            name='verified_by',
            field=models.ForeignKey(help_text='The user who verified the closure of the movement order.', on_delete=django.db.models.deletion.CASCADE, related_name='verified_closures', to='users.customuser'),
        ),
    ]
