# Generated by Django 4.2.10 on 2024-03-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_battery_registration_date_and_more'),
        ('maintenance_manuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancemanual',
            name='vehicle',
            field=models.ForeignKey(help_text='The vehicle to which the maintenance manual belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_manual', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='maintenanceoperation',
            name='maintenance_manual',
            field=models.ForeignKey(help_text='Maintenance manual to which this system belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='manual_tasks', to='maintenance_manuals.maintenancemanual'),
        ),
    ]
