# Generated by Django 4.2.10 on 2024-03-26 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_manuals', '0002_alter_maintenancemanual_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancemanual',
            name='advance_alerts_days',
        ),
        migrations.RemoveField(
            model_name='maintenancemanual',
            name='advance_alerts_mileage',
        ),
        migrations.RemoveField(
            model_name='maintenancemanual',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='maintenanceoperation',
            name='frequency_days',
        ),
        migrations.AddField(
            model_name='maintenancemanual',
            name='advance_alerts',
            field=models.CharField(default='-,-,-', help_text='Using this value it is possible to anticipate maintenance in advance.', max_length=64, validators=[django.core.validators.RegexValidator('^(\\d+(([hkn]{0,1}|da)m(i){0,1})|\\-),(\\d+(([hkn]{0,1}|da)m(i){0,1})|\\-),(\\d{1,4}(h|d|w|m|y)|\\-)$')], verbose_name='Advance alerts'),
        ),
        migrations.AddField(
            model_name='maintenancemanual',
            name='manual_file',
            field=models.FileField(blank=True, help_text='The original maintenance manual document.', null=True, upload_to='manuals/'),
        ),
        migrations.AlterField(
            model_name='maintenancemanual',
            name='end_of_cycle',
            field=models.CharField(default='-,-,-', help_text='The mileage/time limit that marks the end of each maintenance cycle.', max_length=64, validators=[django.core.validators.RegexValidator('^(\\d+(([hkn]{0,1}|da)m(i){0,1})|\\-),(\\d+(([hkn]{0,1}|da)m(i){0,1})|\\-),(\\d{1,4}(h|d|w|m|y)|\\-)$')], verbose_name='End of maintenance cycle'),
        ),
        migrations.AlterField(
            model_name='maintenancemanual',
            name='minimum_frequency',
            field=models.CharField(default='-,-,-', help_text='The minimum mileage/time at which operations should be performed.', max_length=64, validators=[django.core.validators.RegexValidator('^(\\d+(([hkn]{0,1}|da)m(i){0,1})|\\-),(\\d+(([hkn]{0,1}|da)m(i){0,1})|\\-),(\\d{1,4}(h|d|w|m|y)|\\-)$')], verbose_name='Minimum frequency'),
        ),
        migrations.AlterField(
            model_name='maintenanceoperation',
            name='frequency',
            field=models.CharField(default='-,-,-', help_text='The mileage at which the operation should be performed.', max_length=64, validators=[django.core.validators.RegexValidator('^(\\d+(([hkn]{0,1}|da)m(i){0,1})|\\-),(\\d+(([hkn]{0,1}|da)m(i){0,1})|\\-),(\\d{1,4}(h|d|w|m|y)|\\-)$')], verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='maintenanceoperation',
            name='task',
            field=models.CharField(choices=[('I', 'Inspect and correct or replace if necessary.'), ('A', 'Adjust.'), ('R', 'Replace or change.'), ('T', 'Tighten to specified torque.'), ('L', 'Lubricate and/or grease.'), ('C', 'Clean.'), ('CK', 'Check.'), ('TS', 'Test.'), ('SV', 'Service.')], help_text='The task to be performed in the operation.', max_length=50, verbose_name='Task'),
        ),
    ]
