# Generated by Django 4.2.10 on 2024-04-05 03:20

from django.db import migrations, models
import django.db.models.deletion
import maintenance_manuals.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_front_photo_vehicle_heavy_transport_permit_and_more'),
        ('maintenance_manuals', '0003_remove_maintenancemanual_advance_alerts_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancemanual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='maintenancemanual',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='maintenancemanual',
            name='muid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID of the maintenance manual', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='maintenancemanual',
            name='vehicle_type',
            field=models.ForeignKey(default=1, help_text='The vehicle type to which the maintenance manual belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_type_manual', to='vehicles.vehicletype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancemanual',
            name='manual_file',
            field=models.FileField(blank=True, help_text='The original maintenance manual document.', null=True, upload_to=maintenance_manuals.utils.path_and_rename),
        ),
    ]
