# Generated by Django 4.2.10 on 2024-04-05 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_manuals", "0004_remove_maintenancemanual_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceoperation",
            name="maintenance_manual",
            field=models.ForeignKey(
                help_text="Maintenance manual to which this system belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_tasks",
                to="maintenance_manuals.maintenancemanual",
                to_field="muid",
            ),
        ),
    ]
