# Generated by Django 4.2.10 on 2024-04-05 04:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_manuals', '0005_alter_maintenanceoperation_maintenance_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceoperation',
            name='maintenance_manual',
        ),
        migrations.AddField(
            model_name='maintenanceoperation',
            name='manual',
            field=models.ForeignKey(default=uuid.uuid4, help_text='Maintenance manual to which this system belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='manual_tasks', to='maintenance_manuals.maintenancemanual'),
        ),
    ]
