# Generated by Django 4.2.7 on 2024-01-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicletype_engine_displacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='registration_date',
            field=models.PositiveBigIntegerField(default=1706628456, help_text='The date the item was registered'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='registration_date',
            field=models.PositiveBigIntegerField(default=1706628456, help_text='The date the item was registered'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray')], default='white', help_text='Color of the vehicle', max_length=31),
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='status_updated_at',
            field=models.PositiveBigIntegerField(default=1706628456, help_text='The date the status was updated'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('van', 'Van'), ('bus', 'Bus'), ('bicycle', 'Bicycle')], default='car', help_text='Type of the vehicle', max_length=31),
        ),
    ]
