# Generated by Django 4.2.7 on 2024-01-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_battery_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='registration_date',
            field=models.PositiveBigIntegerField(help_text='The date the item was registered'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='registration_date',
            field=models.PositiveBigIntegerField(help_text='The date the item was registered'),
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='status_updated_at',
            field=models.PositiveBigIntegerField(help_text='The date the status was updated'),
        ),
    ]
