# Generated by Django 4.2.10 on 2024-03-25 17:03

import django.core.validators
from django.db import migrations, models
import vehicles.utils


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_battery_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='front_photo',
            field=models.ImageField(blank=True, help_text='Front photo of the vehicle', null=True, upload_to=vehicles.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='heavy_transport_permit',
            field=models.FileField(blank=True, help_text='Heavy transport permit of the vehicle', null=True, upload_to=vehicles.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='left_side_photo',
            field=models.ImageField(blank=True, help_text='Left side photo of the vehicle', null=True, upload_to=vehicles.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rear_photo',
            field=models.ImageField(blank=True, help_text='Rear photo of the vehicle', null=True, upload_to=vehicles.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='right_side_photo',
            field=models.ImageField(blank=True, help_text='Right side photo of the vehicle', null=True, upload_to=vehicles.utils.path_and_rename),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='FFFFFF', help_text='Color of the vehicle in hexadecimal', max_length=6, validators=[django.core.validators.RegexValidator('^[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='city_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.0', help_text='City fuel efficiency', max_digits=5),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='highway_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.0', help_text='Highway fuel efficiency', max_digits=5),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='mixed_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.0', help_text='Mixed fuel efficiency', max_digits=5),
        ),
    ]
