# Generated by Django 4.2.7 on 2024-01-30 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import licenses.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('A1', 'A1'), ('C', 'C'), ('C1', 'C1'), ('D', 'D'), ('D1', 'D1'), ('E', 'E'), ('E1', 'E1'), ('F', 'F')], help_text='The type of the license (A, B, C, etc.).', max_length=2)),
                ('issue_date', models.DateField(help_text='The issue date of the license.', validators=[licenses.validators.validate_issue_date])),
                ('expiry_date', models.DateField(help_text='The expiry date of the license.', validators=[licenses.validators.validate_license_validity])),
                ('points', models.PositiveSmallIntegerField(help_text='Current points of the license.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('driver', models.ForeignKey(help_text='Driver to whom this license belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='users.customuser')),
            ],
        ),
    ]
