# Generated by Django 4.2.10 on 2024-03-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Upload the back image of the license.', null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='license',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Upload the front image of the license.', null=True, upload_to='licenses/'),
        ),
    ]
