# Generated by Django 4.2.7 on 2024-01-31 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0004_alter_battery_registration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.DecimalField(decimal_places=2, help_text='The mileage traveled by the vehicle.', max_digits=10, verbose_name='Mileage')),
                ('unit', models.CharField(choices=[('km', 'Kilometers'), ('mi', 'Miles'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], help_text='The unit of measure of the mileage.', max_length=10, verbose_name='Unit')),
                ('unix_time_registered', models.PositiveBigIntegerField(help_text='The date when the mileage was registered.', verbose_name='Date')),
                ('vehicle', models.ForeignKey(help_text='The vehicle to which the odometer belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='mileage_log', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Mileage',
                'verbose_name_plural': 'Mileages',
            },
        ),
    ]
