# Generated by Django 4.2.10 on 2024-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='unit',
            field=models.CharField(choices=[('m', 'Meters'), ('km', 'Kilometers'), ('mi', 'Miles'), ('nmi', 'Nautical Miles'), ('min', 'Minutes'), ('h', 'Hours'), ('d', 'Days'), ('w', 'Weeks'), ('mo', 'Months'), ('y', 'Years')], help_text='The unit of measure of the mileage.', max_length=10, verbose_name='Unit'),
        ),
    ]
